# Unified Application Configuration
application:
  name: DevOpsSimulator
  version: 3.0.0-experimental
  environment: development
  experimental_mode: true

server:
  host: 0.0.0.0
  port: 9000
  ssl_enabled: true
  hot_reload: true
  multi_port: [9000, 9001, 9002]

logging:
  level: DEBUG
  format: structured
  output: console
  ai_analysis: enabled
  show_stack_trace: true

database:
  host: cluster.example.com
  port: 5432
  name: devops_dev
  distributed: true

features:
  auto_scaling: advanced
  load_balancer: ai-optimized
  backup_enabled: true
  experimental_features: true
  chaos_engineering: enabled

ai_features:
  predictive_scaling: true
  anomaly_detection: true
  auto_optimization: true
  model_version: "v2.1.0"

cloud_providers:
  - aws
  - azure
  - gcp
  - digitalocean

security:
  zero_trust: enabled
  encryption: AES-256
  audit_logging: comprehensive

development:
  mock_external_apis: true
  debug_mode: true
  cors_enabled: true

notifications:
  slack_webhook: "https://hooks.slack.com/services/XXX"
  discord_webhook: "https://discord.com/api/webhooks/YYY"
  email_alerts: false
